### PR TITLE
Fix errors in preview and spawning of the first pins.

### PR DESCRIPTION
**Pull request by firecerne**
When placing a pin on a newly generated project, it placed it on the wrong side.
Now it should be fixed, but I'm not sure since I didn't test with last update.

### CODE REVIEW

**Comment by firecerne** [comment]
Resolved merge issues, I think.

**Comment by firecerne** [comment]
sorry merge issues still there, trying to resolve them

**Comment by UkrainianBanderasCat** [comment]
Waiiittt, It deleted all that i did(localization and random chip)

**Comment by firecerne** [comment]
you were'nt supposed to merge it !

**Pull request merged**
